### ISSUE TITLE
Network policies may block traffic

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener-extension-networking-calico#16]
**What happened**:
End-users might deploy network policies that may block traffic for calico components:

```yaml
$ ks get pod
NAME                                                  READY   STATUS             RESTARTS   AGE
...
calico-typha-vertical-autoscaler-7b9954b9df-8v8kd     0/1     CrashLoopBackOff   8960       35d
...
```

**What you expected to happen**:
Calico components work as expected even if a user deploys custom network policies.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy a network policy that e.g. forbids outgoing traffic for the calico-vpa.

**Anything else we need to know?**:
Related to https://github.com/gardener/gardener/issues/565.

- Gardener version (if relevant): v1.1.5
- Kubernetes version (use `kubectl version`): all
- Cloud provider or hardware configuration: all

**Comment by zanetworker** [comment]
@rfranzke the issue is that the blocking policy is in fact in the `default` namespace where our kubernetes endpoint is, as a result all ingress traffic in that namespace is blocked (including the requests to watch for stuff to the API-server).

**Comment by rfranzke** [comment]
Thanks for digging into it! So #16 will fix it?

**Comment by zanetworker** [comment]
it should after the provided review.

**Comment by rfranzke** [comment]
Great, thanks! :)
