### ISSUE TITLE
Controller reports unhealthy system components

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener-extension-networking-calico#160]
**How to categorize this issue?**

/area networking
/ops-productivity
/kind bug

**What happened**:
We regularly experience the `SystemComponentsHealthy` of a shoot cluster being set to `False` with the following message:

```
Network extension (shoot--foo--bar/bar) reports
failing health check: managed resource
"extension-networking-calico-config" in namespace
"shoot--foo--bar" is unhealthy: DaemonSet
"kube-system/calico-node" is unhealthy: unready pods found (70/71), 55
pods updated (DaemonSetUnhealthy).
```

Most of the time this unhealthy condition is reported because the DaemonSet was just updated by the `calico-node-vertical-autoscaler` and thus a rolling update with `maxUnavailable: 1` is performed. This rollout takes longer than the grace period considered by the controller's health check.

**What you expected to happen**:
The condition should not be reported as `False`, i.e. it should be more tolerant when a rolling update happens. Operators are distracted by these false positives and thus "real" issues can be missed easily.

**Environment**:

- Gardener version (if relevant):  v1.41.2
- Extension version: v1.19.7

**Comment by DockToFuture** [comment]
Was fixed in https://github.com/gardener/gardener/pull/5628
