### ISSUE TITLE
Enabling SecurityContextDeny Admission Plugin results in Calico failure

### ISSUE THREAD

**Issue by rafalpotempa** [gardener/gardener-extension-networking-calico#19]
**Desciption**
Creating Shoot with _Calico_ and _SecurityContextDeny_ Admission Plungin results in Calico being unable to setup and probably blocking Tiller traffic.

_SecurityContextDeny_ disallows `allowPrivilegeEscalation: true`, meanwhile in gardener-extensions it is set to `true`:
https://github.com/gardener/gardener-extension-networking-calico/blob/295ee63b0ec61b106fec7b9f4b500278db1317e2/charts/internal/calico/templates/kube-controller/deployment-calico-kube-controllers.yaml#L72

**Expected results**
Calico and Tiller setup successful.

**Actual result**
- `calico-kube-controllers-asdadsgd` pod `CrashLoopBackOff`.
- Tiller certs setup failure due to timeout connecting `kubernetes` service.

**Steps to reproduce**
Provision cluster with _Calico_ and _SecurityContextDeny_ Admission Plugin.

- AllowPrivilegegContainer: true
- KubernetesVersion: 1.15.10
- KubeAPIServer:
  - EnableBasicAuthentication: false
- Networking:
  - Type: "calico"
  - Nodes: "10.250.0.0/19"

**Comment by rfranzke** [comment]
See also: https://github.com/gardener/gardener/issues/2047

**Comment by zanetworker** [comment]
@rafalpotempa will close since `SecurityContextDeny` cannot work with `podSecurityPolicies`, please re-open if you think this is still a valid issue.
