### ISSUE TITLE
Leverage VPA for calico components

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener-extension-networking-calico#38]
**How to categorize this issue?**

/kind enhancement
/priority normal
/area networking

**What would you like to be added**:
With https://github.com/gardener/gardener/pull/2478 Gardener will add support for the VPA for shoot clusters.
The calico extension is relying on other components for horizontal and vertical autoscaling, ref https://github.com/gardener/gardener-extension-networking-calico/blob/master/charts/images.yaml#L22-L28.
Probably it would make sense to only use them if the shoot does not enable VPA, and otherwise use the VPA directly instead of deploying these additional components.

**Why is this needed**:
Scalability.

**Comment by zanetworker** [comment]
@rfranzke do you think we will be enabling the VPA soon by default for shoot clusters? 

What I am thinking is that we can wait till its enabled by default and completely switch to VPA (and remove all the cvpa) pods. That said, both autoscalers do not overlap in functionality, the CVPA has the advantage of not relying on having the metrics server available to work correctly, nor does it required CPU resources to be explicitly defined (but we do that anyways), but if we think VPA is the way to go then why not.

**Comment by rfranzke** [comment]
Probably not too soon, it will take a while because end-users might have their own VPA deployments and we need to allow them preparing for the "enabled by default" change in a reasonable time frame. But even if, for an even longer time it will still be configurable via the `Shoot` and users could disable it. So we need to keep the CVPA anyways for a longer while. Still, when user enables VPA we could simply leverage it and deploy one component less that can potentially fail and consumes resources. I cannot judge whether there is a huge difference between CVPA and VPA function-wise (cc @ggaurav10 @wyb1 @amshuman-kr), but those two points would be my motivation.

**Comment by ScheererJ** [comment]
Implemented in https://github.com/gardener/gardener-extension-networking-calico/pull/286.
