### ISSUE TITLE
Relationship between gardener-extension-networking-calico & Shoot Defination

### ISSUE THREAD

**Issue by syy6** [gardener/gardener-extension-networking-calico#48]
Hi, 
When we create the shoot in Gardener, it seems that we can define
networking:
    type: calico
    nodes: 10.250.0.0/16
or even
networking:
    type: calico
    nodes: 10.44.0.0/20
    pods: 172.16.0.0/11
    services: 172.17.0.0/13
I also noticed there is this Gardener calico network extention  but it seems that the configuration in this extention is different if we compare with its document like https://github.com/gardener/gardener-extension-networking-calico/blob/master/example/20-network.yaml#L37
So, could u please share with us if the defination in Shoot is actually be used by this extention of it's totally different things at all?
Or is there is any document to explain the networking defination in Garderner Shoot? It seems that I can't find any detail on Gardener Website. 
Meanwhile, for this gardener-extension-networking-calico, in the README.md, the defination is like
spec:
  type: calico
  clusterCIDR: 192.168.0.0/24
  serviceCIDR:  10.96.0.0/24
But in the example mentioned above(https://github.com/gardener/gardener-extension-networking-calico/blob/master/example/20-network.yaml#L37) is like
spec:
  type: calico
  podCIDR: 10.244.0.0/16
  serviceCIDR:  10.96.0.0/24
If there is some document explain what's the difference betwen clusterCIDR, serviceCIDR and podCIDR and the usuage?
Thanks!
BR,
Yongyuan

**Comment by zanetworker** [comment]
@syy6 do you still have the concern after the explanation on slack?

**Comment by vpnachev** [comment]
@syy6 I will close this issue now. If you need more help, please re-open it.
/close
