### ISSUE TITLE
calico-typha-vertical-autoscaler in CrashLoopBackOff when deployments is available under multiple API groups

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extension-networking-calico#8]
**What happened**:
calico-typha-vertical-autoscaler fails when deployments is available under multiple API groups.

**How to reproduce it (as minimally and precisely as possible)**:
1. Install linkerd. See https://linkerd.io/2/getting-started/

2. Ensure that there are multiple API groups serving resource `deployments`:

```
$ k api-resources
NAME                              SHORTNAMES   APIGROUP                       NAMESPACED   KIND
# ...
daemonsets                        ds           apps                           true         DaemonSet
deployments                       deploy       apps                           true         Deployment
# ...
daemonsets                        ds           tap.linkerd.io                 true         Tap
deployments                       deploy       tap.linkerd.io                 true         Tap
```

3. Ensure that `calico-typha-vertical-autoscaler` fails with

```
$ k logs calico-typha-vertical-autoscaler-7b9954b9df-ptrpq -n kube-system
I0217 20:41:29.699612       1 autoscaler.go:46] Scaling namespace: kube-system, target: deployment/calico-typha-deploy
E0217 20:41:30.799782       1 autoscaler.go:49] unknown target kind: Tap
```

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant):
- Extension version: v1.3.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by zanetworker** [comment]
do you think it makes sense to file an issue here as well: https://github.com/kubernetes-incubator/cluster-proportional-vertical-autoscaler ?

**Comment by zanetworker** [comment]
@ialidzhikov any update on this one?

**Comment by dkhodakivskyi** [comment]
I am also interested in it.... any updates?

**Comment by ialidzhikov** [comment]
I opened https://github.com/kubernetes-incubator/cluster-proportional-vertical-autoscaler/issues/31
